# 1.03 — Data manipulation with NumPy & pandas

## What’s the difference?
**NumPy**
- Core object: **`ndarray`** (n-dimensional array)
- Best for: fast numerical computing, vectors/matrices, linear algebra, broadcasting
- Think: *math with arrays*

**pandas**
- Core objects: **`Series`** (1D) and **`DataFrame`** (2D table)
- Best for: tabular data, column names, missing values, joins/merges, groupby/aggregation
- Think: *Excel-like tables + data cleaning*

![pandas vs numpy](images/numpy_pandas.png)

## Quick rule of thumb
- Use **NumPy** when your data is mostly numeric and you want fast array math.
- Use **pandas** when your data has columns (possibly mixed types) and you need filtering, grouping, merging, or cleaning.

In [ ]:
! pip install numpy pandas

In [2]:
# Setup
import numpy as np
import pandas as pd

np.__version__, pd.__version__

('2.2.6', '2.2.2')

## NumPy demo (arrays = fast math)
We’ll create arrays, slice them, and apply vectorized operations (no Python loops).

#### 1. Create arrays

In [5]:
list_a = [1, 2, 3, 4, 5]
list_b = [10, 20, 30, 40, 50]

In [6]:
list_a + list_b

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [7]:
a = np.array(list_a)
b = np.array(list_b)
print('a:', a)
print('b:', b)

a: [1 2 3 4 5]
b: [10 20 30 40 50]

#### 2. Vectorized operations (element-wise)

In [8]:

print('a + b:', a + b)
print('a * 2:', a * 2)

a + b: [11 22 33 44 55]
a * 2: [ 2  4  6  8 10]

#### 3. Boolean filtering

In [11]:

mask = a >= 3
print('mask:', mask)
print('a[a>=3]:', a[mask])

mask: [False False  True  True  True]
a[a>=3]: [3 4 5]

#### 4. 2D array + slicing

In [12]:

m = np.array([[1, 2, 3], [4, 5, 6]])
print('m:\n', m)
print('first row:', m[0, :])
print('second column:', m[:, 1])

m:
 [[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second column: [2 5]

## pandas demo (tables = labeled columns)
#### 1.Create a small DataFrame

In [ ]:
df_small = pd.DataFrame({
    'name': ['John', 'Emily', 'Michael', 'Sophia'],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'score': [14, 17, 15, 9],
})
df_small

      name        city  score
0      Ali       Rabat     14
1     Mina  Casablanca     17
2     Sara       Rabat     15
3  Youssef   Marrakech      9

#### 2. Select columns / rows

In [16]:
print(df_small[['name', 'score']])

      name  score
0      Ali     14
1     Mina     17
2     Sara     15
3  Youssef      9

#### 3. print score high to 15

In [17]:
high_score = df_small[df_small['score'] >= 15]
print('\nscore >= 15')
print(high_score)

score >= 15
   name        city  score
1  Mina  Casablanca     17
2  Sara       Rabat     15

#### 4. Create a new column

In [18]:
df_small['passed'] = df_small['score'] >= 10
print('\nwith passed column')
print(df_small)

with passed column
      name        city  score  passed
0      Ali       Rabat     14    True
1     Mina  Casablanca     17    True
2     Sara       Rabat     15    True
3  Youssef   Marrakech      9   False

In [19]:
# Groupby: average score per city
avg_by_city = df_small.groupby('city', as_index=False)['score'].mean()
print('\naverage score by city')
print(avg_by_city)

average score by city
         city  score
0  Casablanca   17.0
1   Marrakech    9.0
2       Rabat   14.5

### manipulation data using pandas, import

#### 4. import data from csv file and print the 5 first rows and 5 last rows

In [21]:
data_frame = pd.read_csv('data/data_lab_1.03.csv')

In [22]:
data_frame.head(5)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [23]:
data_frame.tail(5)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

### print the columns

In [24]:
data_frame.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

### select the dataframe with numerical data

In [25]:
data_frame_numeric = data_frame.select_dtypes(include=['number'])   
data_frame_numeric

     math_score  reading_score  writing_score
0            72             72             74
1            69             90             88
2            90             95             93
3            47             57             44
4            76             78             75
..          ...            ...            ...
995          88             99             95
996          62             55             55
997          59             71             65
998          68             78             77
999          77             86             86

[1000 rows x 3 columns]

#### describe the numerical values

In [27]:
data_frame_numeric.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

#### categorical features

In [29]:
data_frame_categorical = data_frame.select_dtypes(include=['object'])   

data_frame_categorical

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course
0,female,group B,bachelor's degree,standard,none
1,female,group C,some college,standard,completed
2,female,group B,master's degree,standard,none
3,male,group A,associate's degree,free/reduced,none
4,male,group C,some college,standard,none
...,...,...,...,...,...
995,female,group E,master's degree,standard,completed
996,male,group C,high school,free/reduced,none
997,female,group C,high school,free/reduced,completed
998,female,group D,some college,standard,completed
999,female,group D,some college,free/reduced,none

### do some values count to see the number of each category

In [34]:
print('*****gender count********\n', data_frame_categorical.gender.value_counts())
print('*****race_ethnicity count********\n', data_frame_categorical.race_ethnicity.value_counts())
print('*****parental_level_of_education count********\n', data_frame_categorical.parental_level_of_education.value_counts())
print('*****lunch count********\n', data_frame_categorical.lunch.value_counts())
print('*****test_preparation_course count********\n', data_frame_categorical.test_preparation_course.value_counts())

*****gender count********
 gender
female    518
male      482
Name: count, dtype: int64
*****race_ethnicity count********
 race_ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64
*****parental_level_of_education count********
 parental_level_of_education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64
*****lunch count********
 lunch
standard        645
free/reduced    355
Name: count, dtype: int64
*****test_preparation_course count********
 test_preparation_course
none         642
completed    358
Name: count, dtype: int64

## NumPy ↔ pandas (how they work together)
- A pandas `DataFrame` stores columns as NumPy-like arrays internally.
- Use **pandas** for labels + missing values + table operations.
- Use **NumPy** for fast numeric math once you have clean numeric arrays.

In [36]:
# Convert a DataFrame column to NumPy, do math, and put it back
scores_np = data_frame['math_score'].to_numpy()
print('scores_np type:', type(scores_np), 'values:', scores_np)

scores_np type: <class 'numpy.ndarray'> values: [ 72  69  90  47  76  71  88  40  64  38  58  40  65  78  50  69  88  18
  46  54  66  65  44  69  74  73  69  67  70  62  69  63  56  40  97  81
  74  50  75  57  55  58  53  59  50  65  55  66  57  82  53  77  53  88
  71  33  82  52  58   0  79  39  62  69  59  67  45  60  61  39  58  63
  41  61  49  44  30  80  61  62  47  49  50  72  42  73  76  71  58  73
  65  27  71  43  79  78  65  63  58  65  79  68  85  60  98  58  87  66
  52  70  77  62  54  51  99  84  75  78  51  55  79  91  88  63  83  87
  72  65  82  51  89  53  87  75  74  58  51  70  59  71  76  59  42  57
  88  22  88  73  68 100  62  77  59  54  62  70  66  60  61  66  82  75
  49  52  81  96  53  58  68  67  72  94  79  63  43  81  46  71  52  97
  62  46  50  65  45  65  80  62  48  77  66  76  62  77  69  61  59  55
  45  78  67  65  69  57  59  74  82  81  74  58  80  35  42  60  87  84
  83  34  66  61  56  87  55  86  52  45  72  57  68  88  76  46  67  92
  83  80  63  64  54  84  73  80  56  59  75  85  89  58  65  68  47  71
  60  80  54  62  64  78  70  65  64  79  44  99  76  59  63  69  88  71
  69  58  47  65  88  83  85  59  65  73  53  45  73  70  37  81  97  67
  88  77  76  86  63  65  78  67  46  71  40  90  81  56  67  80  74  69
  99  51  53  49  73  66  67  68  59  71  77  83  63  56  67  75  71  43
  41  82  61  28  82  41  71  47  62  90  83  61  76  49  24  35  58  61
  69  67  79  72  62  77  75  87  52  66  63  46  59  61  63  42  59  80
  58  85  52  27  59  49  69  61  44  73  84  45  74  82  59  46  80  85
  71  66  80  87  79  38  38  67  64  57  62  73  73  77  76  57  65  48
  50  85  74  60  59  53  49  88  54  63  65  82  52  87  70  84  71  63
  51  84  71  74  68  57  82  57  47  59  41  62  86  69  65  68  64  61
  61  47  73  50  75  75  70  89  67  78  59  73  79  67  69  86  47  81
  64 100  65  65  53  37  79  53 100  72  53  54  71  77  75  84  26  72
  77  91  83  63  68  59  90  71  76  80  55  76  73  52  68  59  49  70
  61  60  64  79  65  64  83  81  54  68  54  59  66  76  74  94  63  95
  40  82  68  55  79  86  76  64  62  54  77  76  74  66  66  67  71  91
  69  54  53  68  56  36  29  62  68  47  62  79  73  66  51  51  85  97
  75  79  81  82  64  78  92  72  62  79  79  87  40  77  53  32  55  61
  53  73  74  63  96  63  48  48  92  61  63  68  71  91  53  50  74  40
  61  81  48  53  81  77  63  73  69  65  55  44  54  48  58  71  68  74
  92  56  30  53  69  65  54  29  76  60  84  75  85  40  61  58  69  58
  94  65  82  60  37  88  95  65  35  62  58 100  61 100  69  61  49  44
  67  79  66  75  84  71  67  80  86  76  41  74  72  74  70  65  59  64
  50  69  51  68  85  65  73  62  77  69  43  90  74  73  55  65  80  50
  63  77  73  81  66  52  69  65  69  50  73  70  81  63  67  60  62  29
  62  94  85  77  53  93  49  73  66  77  49  79  75  59  57  66  79  57
  87  63  59  62  46  66  89  42  93  80  98  81  60  76  73  96  76  91
  62  55  74  50  47  81  65  68  73  53  68  55  87  55  53  67  92  53
  81  61  80  37  81  59  55  72  69  69  50  87  71  68  79  77  58  84
  55  70  52  69  53  48  78  62  60  74  58  76  68  58  52  75  52  62
  66  49  66  35  72  94  46  77  76  52  91  32  72  19  68  52  48  60
  66  89  42  57  70  70  69  52  67  76  87  82  73  75  64  41  90  59
  51  45  54  87  72  94  45  61  60  77  85  78  49  71  48  62  56  65
  69  68  61  74  64  77  58  60  73  75  58  66  39  64  23  74  40  90
  91  64  59  80  71  61  87  82  62  97  75  65  52  87  53  81  39  71
  97  82  59  61  78  49  59  70  82  90  43  80  81  57  59  64  63  71
  64  55  51  62  93  54  69  44  86  85  50  88  59  32  36  63  67  65
  85  73  34  93  67  88  57  79  67  70  50  69  52  47  46  68 100  44
  57  91  69  35  72  54  74  74  64  65  46  48  67  62  61  70  98  70
  67  57  85  77  72  78  81  61  58  54  82  49  49  57  94  75  74  58
  62  72  84  92  45  75  56  48 100  65  72  62  66  63  68  75  89  78
  53  49  54  64  60  62  55  91   8  81  79  78  74  57  40  81  44  67
  86  65  55  62  63  88  62  59  68  77]

In [37]:
z = (scores_np - scores_np.mean()) / scores_np.std()  # simple normalization
data_frame['math_score_z'] = z
data_frame.head(5)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_z
0,female,group B,bachelor's degree,standard,none,72,72,74,0.390024
1,female,group C,some college,standard,completed,69,90,88,0.192076
2,female,group B,master's degree,standard,none,90,95,93,1.577711
3,male,group A,associate's degree,free/reduced,none,47,57,44,-1.259543
4,male,group C,some college,standard,none,76,78,75,0.653954