# LAB 1.07 Data Collection (Database)

### Import Required Libraries

In [1]:
import sqlite3
import pandas as pd

### Create a Sample Database (For Students)

In [ ]:
# Create SQLite database
conn = sqlite3.connect("data/ml_course.db")
cursor = conn.cursor()

# Create table
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER PRIMARY KEY,
    age INTEGER,
    income REAL,
    city TEXT,
    purchased INTEGER
)
""")

# Insert sample data
data = [
    (25, 30000, "Paris", 0),
    (35, 55000, "London", 1),
    (45, 70000, "Berlin", 1),
    (23, 28000, "Madrid", 0),
    (50, 90000, "Rome", 1)
]

cursor.executemany(
    "INSERT INTO customers (age, income, city, purchased) VALUES (?, ?, ?, ?)",
    data
)

conn.commit()

### Read Data from Database (SQL → pandas)

In [3]:
query = "SELECT * FROM customers"
df = pd.read_sql(query, conn)

df

   customer_id  age   income    city  purchased
0            1   25  30000.0   Paris          0
1            2   35  55000.0  London          1
2            3   45  70000.0  Berlin          1
3            4   23  28000.0  Madrid          0
4            5   50  90000.0    Rome          1

### Filtering Data Using SQL

In [4]:
query = """
SELECT age, income, purchased
FROM customers
WHERE income > 40000
"""

df_filtered = pd.read_sql(query, conn)
df_filtered

   age   income  purchased
0   35  55000.0          1
1   45  70000.0          1
2   50  90000.0          1

### Basic Data Preparation

In [5]:
X = df[["age", "income"]]
y = df["purchased"]

print("Features:")
display(X)

print("Target:")
display(y)

Features:

   age   income
0   25  30000.0
1   35  55000.0
2   45  70000.0
3   23  28000.0
4   50  90000.0

Target:

0    0
1    1
2    1
3    0
4    1
Name: purchased, dtype: int64

### Close connection

In [6]:
conn.close()